CREATE TABLE IF NOT EXISTS nda_submissions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT NOT NULL UNIQUE,
  nda_version TEXT NOT NULL,
  nda_text_hash TEXT NOT NULL,
  nda_text_snapshot TEXT NOT NULL,
  legal_name TEXT NOT NULL,
  address_line_1 TEXT NOT NULL,
  address_line_2 TEXT,
  city TEXT NOT NULL,
  state_province TEXT NOT NULL,
  postal_code TEXT NOT NULL,
  country TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  business_name TEXT NOT NULL,
  business_website TEXT NOT NULL,
  facebook_profile TEXT NOT NULL,
  testing_phase TEXT NOT NULL,
  vouching_designer_name TEXT,
  vouching_designer_business TEXT,
  vouching_designer_facebook TEXT,
  vouching_designer_email TEXT,
  vouching_designer_relationship TEXT,
  initials_json TEXT NOT NULL,
  typed_signature_name TEXT NOT NULL,
  signature_data TEXT NOT NULL,
  signature_file_path TEXT,
  confirm_info_accurate INTEGER NOT NULL DEFAULT 0,
  confirm_read_understood_agreed INTEGER NOT NULL DEFAULT 0,
  confirm_legal_action INTEGER NOT NULL DEFAULT 0,
  confirm_no_disclosure INTEGER NOT NULL DEFAULT 0,
  ip_address TEXT,
  user_agent TEXT,
  submitted_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_nda_submissions_submitted_at ON nda_submissions(submitted_at);
CREATE INDEX IF NOT EXISTS idx_nda_submissions_email ON nda_submissions(email);
